name: Build & Deploy multi-subpath apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            genmdm-explorer/package.json
            arduinoboy/package.json
            ym2149f-turbo-sound-x3/package.json

      - name: Install deps (GenMDM)
        working-directory: genmdm-explorer
        run: npm install

      - name: Build (GenMDM)
        working-directory: genmdm-explorer
        run: npm run build

      - name: Install deps (Arduinoboy)
        working-directory: arduinoboy
        run: npm install

      - name: Build (Arduinoboy)
        working-directory: arduinoboy
        run: npm run build

      - name: Install deps (YM2149F x3)
        working-directory: ym2149f-turbo-sound-x3
        run: npm install

      - name: Build (YM2149F x3)
        working-directory: ym2149f-turbo-sound-x3
        run: npm run build

      - name: Prepare Pages artifact
        run: |
          mkdir -p site/genmdm-explorer site/arduinoboy site/ym2149f-turbo-sound-x3
          cp -r genmdm-explorer/dist/* site/genmdm-explorer/
          cp -r arduinoboy/dist/* site/arduinoboy/
          cp -r ym2149f-turbo-sound-x3/dist/* site/ym2149f-turbo-sound-x3/
          # root index
          if [ -f index.html ]; then cp index.html site/index.html; fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
